version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:6.10-browsers
    steps:
      -checkout
      - run: npm install && npm build
  deploy-job:
    docker:
      - image: circleci/node:6.10-browsers
    steps:
      - run:
          name: Install dependencies
          working_directory: /
          command: sudo apt-get -y -qq install awscli
      - checkout
      - run:
          name: Install and build
          command: npm build
      - run:
          name: Deploy if tests pass and branch is Master
          command: aws s3 sync build s3://sizzling-plate/ --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
