version: 2
jobs:
  test-job:
    docker:
      - image: circleci/node:6.10-browsers
    steps:
      - checkout
      - run: npm install
      - run:
          name: Test
          command: npm test
  deploy-job:
    docker:
      - image: circleci/node:6.10-browsers
    steps:
      - run:
          name: Install dependencies
          command: sudo apt-get -y -qq install awscli
      - checkout
      # - run:
      #     name: Install
      #     command: npm install
      # - run:
      #     name: Build
      #     command: npm run build
      # - run:
      #     name: Deploy to SizzlingPlate
      #     command: aws s3 sync ./build s3://sizzling-plate/ --delete
      - run:
          name: Deploy to ShowOfHands
          command: aws s3 sync ./src/ s3://showofhands.ml/ --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - test-job
      - deploy-job:
          # requires:
          #   - test-job
          filters:
            branches:
              only: master
