version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:6.10-browsers
    steps:
      - run: npm install && npm build
  deploy-job:
    docker:
      - image: circleci/node:6.10-browsers
    steps:
      - run:
          name: Install dependencies
          working_directory: /
          command: |
            apt-get -y -qq update
            apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            pip install awscli --upgrade --user
      - run:
          name: Deploy if tests pass and branch is Master
          command: aws s3 sync ~/projects/sizzling-plate-client s3://sizzling-plate/ --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
